//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTableProjectApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friday
    {
        public int Id_lesson { get; set; }
        public string Lesson { get; set; }
        public string Classroom { get; set; }
        public string Teacher { get; set; }
    }
}
